export const EVENTS = {
  ROLE_ASSIGNED: 'ROLE_ASSIGNED',
  SECOND_CATCHER_CONNECTED: 'SECOND_CATCHER_CONNECTED',
};

export const ACTIONS = {
  START: 'START',
  MOVE_CATCHER: 'MOVE_CATCHER',
  RESTART: 'RESTART',
  START_GAME_TIMER: 'START_GAME_TIMER',
  TOGGLE_SOUND: 'TOGGLE_SOUND',
  APPLY_SETTINGS: 'APPLY_SETTINGS'
};